include(FetchContent)

set(ONEDNN_CPU_RUNTIME "SYCL" CACHE STRING "" FORCE)
set(ONEDNN_GPU_RUNTIME "SYCL" CACHE STRING "" FORCE)
set(ONEDNN_BUILD_DOC OFF CACHE BOOL "" FORCE)
set(ONEDNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ONEDNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ONEDNN_BUILD_GRAPH ON CACHE BOOL "" FORCE)
set(ONEDNN_ENABLE_GRAPH_DUMP OFF CACHE BOOL "" FORCE)
set(ONEDNN_ENABLE_WORKLOAD "INFERENCE" CACHE STRING "" FORCE)
set(ONEDNN_GPU_VENDOR "INTEL" CACHE STRING "" FORCE)

FetchContent_Declare(
    dnnl
    GIT_REPOSITORY https://github.com/uxlfoundation/oneDNN.git
    GIT_TAG        fc6151651a4577beae5ffac5a4132e75d39e1409 # v3.11
    GIT_SHALLOW    TRUE
    GIT_PROGRESS   TRUE
    SYSTEM         TRUE
)
FetchContent_MakeAvailable(dnnl)
