include(FetchContent)

set(ONEDNN_CPU_RUNTIME "SYCL" CACHE STRING "" FORCE)
set(ONEDNN_GPU_RUNTIME "SYCL" CACHE STRING "" FORCE)
set(ONEDNN_BUILD_DOC OFF CACHE BOOL "" FORCE)
set(ONEDNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ONEDNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ONEDNN_ENABLE_WORKLOAD "INFERENCE" CACHE STRING "" FORCE)

# Define GPU vendor as NONE, INTEL, NVIDIA (AMD: no graph support yet)
set(ONEDNN_GPU_VENDOR "NONE" CACHE STRING "" FORCE)

FetchContent_Declare(
    dnnl
    GIT_REPOSITORY https://github.com/uxlfoundation/oneDNN.git
    GIT_TAG        f1d471933dc852f956fd05389f9313c7148783d5 # v3.10.2
    GIT_SHALLOW    TRUE
    GIT_PROGRESS   TRUE
)
FetchContent_MakeAvailable(dnnl)
